version: '3'
services: 
    db-server:
      image: mariadb
      container_name: em-db
      restart: always
      ports:
        - ${DB_PORT}:3306
      environment:
        MYSQL_ROOT_PASSWORD: admin
      volumes:
        - ./dbdata:/var/lib/mysql

#    myadmin:
#      image: phpmyadmin
#      container_name: dc-phpadmin
#      restart: always
#      ports:
#        - ${MYADMIN_PORT}:80
#      environment:
#        PMA_HOST: db-server

    web-server:
      image: nginx
      container_name: em-nginx
      #restart: always
      ports:
        - ${WEB_SERVER_PORT}:80
      volumes:
        - ../:/var/www/app
        - ./default.conf:/etc/nginx/conf.d/default.conf
      networks:
        - app-network
      depends_on:
        - app

    app:
      build:
        context: ./
        dockerfile: Dockerfile
      container_name: em-app
      ports:
        - "9000"
      volumes:
        - ../:/var/www/app
        - ./supervisor/php-fpm.conf:/etc/supervisor/conf.d/php-fpm.conf
      networks:
        - app-network

networks:
  app-network:
    driver: bridge
